### ISSUE TITLE
1.0 release checklist

### ISSUE THREAD

**Issue by benlk** [INN/link-roundups#158]
- [x] tag prerelease `git tag -s v1.0-rc1`
- [x] Run `release.sh --dry_run`
- [x] push to That Site We're Testing This For, using the `wp-release.zip` generated by that script
    - [x] test that the update-page styles aren't too far off kilter
- [x] Make sure that WordPress MailChimp Tools commit in `composer.json` is the latest master: https://github.com/INN/wordpress-mailchimp-tools/commits/master
- [x] Make sure that the version number has been bumped
    - [x] readme.txt
    - [x] readme.md
    - [ ] ~composer.json~ not recorded
    - [x] package.json
    - [x] link-roundups.php
- [x] Make sure that you have also updated:
	- [x] `Tested up to:` WordPress version number in `readme.txt`
	- [x] `Requires at least:` WordPress version number in `readme.txt`
	- [x] `Requires PHP:` minimum PHP version number in `readme.txt`
	- [x] `Changelog` section in `readme.txt`
	- [x] any INN URLs
	- [x] the WordPress users associated
- [x] test:
	- [x] Saving links
	- [x] Putting links into a roundup
	- [x] sending a roundup (Done by Ben in the WordPress MailChimp Tools ticket)
- [x] Run `release.sh --dry_run`
- [ ] Run `release.sh` for reals

After release
- [ ] update assets dir with new images: https://wordpress.org/plugins/link-roundups/
- [x] blog post
- [x] Nerd Alert note

**Comment by benlk** [comment]
Draft release: https://github.com/INN/link-roundups/releases/edit/untagged-fb91ee7ecaf24b1c64ea

**Comment by benlk** [comment]
Ran release.sh for reals, got a failure to release documented in #170. Now going for 1.0.1.
